tox.ini

pytest dropped `py` as dependency and pytest-xprocess requires it as implicit dependency. As pytest-xprocess relied on pytest to pull it in it now errors when trying to run the murdock tests.
This commit adds `py` to the list of dependencies for tox. It can be reverted as soon as pytest-xprocess adds `py` to the dependency list.
See also: https://github.com/pytest-dev/pytest-xprocess/issues/110

tox: add py to dependencies

---

murdock/main.py
murdock/murdock.py
requirements.txt

This adds python and HTTP statistics to be scraped by a prometheus (or other openmetrics collector) at the `/metrics` endpoint.

murdock: Add basic prometheus instrumentation

---

murdock/config.py
murdock/models.py
murdock/tests/test_database.py

As discussed offline, this forces the environment dicts to use only strings for the content.
The database test is adapted because the model would cast the value to a `str` causing the test to fail.

models: enforce [str, str] typing for environment dicts 

---

docker-compose.yml
traefik/http.yml
traefik/traefik.yml

This PR exposes the murdock frontend metrics and the traefik internal metrics so that they can be scraped by a prometheus instance

Traefik: Expose murdock frontend and traefik internal metrics

---

murdock/murdock.py
murdock/tests/conftest.py
murdock/tests/test_murdock.py
murdock/tests/test_notify.py
setup.cfg

This commit adds counters for the number of jobs added to the queue and
the result status of jobs.
Any job (re-)entering the queue should be counted, intentionally also
counting jobs that were requeued because of a change in the pull
request.
The other counter keeps track of the result of a job. This includes the
passed and errored label if the job completed the build, but also
stopped and canceled if the job was stopped before completing or if the
job was not started yet.
The number of builds currently in the queue should match the difference
between the queue counter and the job status counter

murdock: Add prometheus counters for jobs

---

murdock/murdock.py
murdock/tests/test_murdock.py

This PR adds counters for individual tasks, keeping track of the number of passed and failed tasks submitted to workers.
It includes a fix for the [`handle_job_status_data`](https://github.com/murdock-ng/murdock/commit/dedd1a350432a6b30af05c525f111ca7d880991b) test, making it match the content delivered by the PUT request.
depends on #12

murdock: Add task counter metrics 

---

murdock/murdock.py
murdock/tests/test_murdock.py

Quick bug fix that caused negative load in the CI graphs because stopped jobs are counted twice.

murdock: Don't count stopped jobs twice 

---

murdock/job_containers.py
murdock/murdock.py
murdock/tests/test_murdock.py

This adds a counter for the number of started jobs and a gauge to get the immediate number of jobs running.
As requested by @kaspar030

Murdock: add metrics for number of running jobs

---

Dockerfile
docker-compose.yml

With this it can be configured locally via a docker-compose.override.yml containing:
```
services:
murdock:
environment:
- UVICORN_LOG_LEVEL=warning
```

Docker: Make uvicorn log level configurable

---

murdock/main.py

Github aggresively caches images for READMEs. This results in CI badges updating late or not after a different CI result. Adding the Content-Cache and ETag headers should prevent these badges from lingering too long in the cache.

main: Add no-cache and etag to badge

---

.env.example
docker-compose.api.yml

This adds a docker-compose.api.yml that only starts the API services and the related services such as the database and building the frontend web files. This allows for running only the API components from docker and servicing the other components from external services

docker-compose: Add variant with only API services

---

Dockerfile

Passing the log level through environment variables is sufficient
reverts part of #26

Dockerfile: remove uvicorn log level argument

---

.env.example
murdock/config.py
murdock/database/__init__.py
murdock/database/mongodb.py
murdock/murdock.py
murdock/tests/test_api.py
murdock/tests/test_database.py
murdock/tests/test_murdock.py

Paves the way for implementing alternative database back-ends.
There should be a better way to mock the individual database functions for a database back-end.

Database: Add abstract database class

---

murdock/database/mongodb.py

This resolves a small issue with motor. In turn Murdock can also be started with gunicorn:
```
gunicorn murdock.main:app --worker-class uvicorn.workers.UvicornWorker
```
Without this patch the coroutines from motor would attach to a different event loop, resulting in a runtime error.

mongodb: Make compatible with gunicorn

---

murdock/tests/test_murdock.py

The assert in `test_handle_push_event_ref_not_handled` was inverted,
testing if the error message was *not* present while it should be
present. Previously the test passed because the message was logged at
DEBUG level and not present in the caplog for the test

test_murdock: fix inverted assert in test

---

.env.example
.github/workflows/continuous-integration.yml
murdock/config.py
murdock/database/__init__.py
murdock/database/mongodb.py
murdock/database/postgresql.py
murdock/murdock.py
murdock/tests/conftest.py
murdock/tests/test_database.py
murdock/tests/test_database_mongodb.py
murdock/tests/test_database_postgresql.py
murdock/tests/test_murdock.py
murdock/tests/test_notify.py
requirements.txt

This adds support for Postgresql as relational database backend for the persistent job storage. The implementation makes use of [`asyncpg`](https://pypi.org/project/asyncpg/). Queries are manually written, but can be adapted to an ORM such as sqlalchemy in the future.  There is only two spots where arguments are directly interpolated into the query string: the `LIMIT` clause in the `find_jobs` and the column name in the update. In all other cases the code uses query arguments to prevent SQL injection.
The tests are adapted to run with both postgres and mongodb where applicable. Only the API test runs with only mongodb (as it is the default).
A number of small commits can be split out from this PR if needed, such as 65b368b9a65ac770a1ce700a1bf47df03da5a604, …

 database: Add postgres backend 

---

.github/workflows/continuous-integration.yml
Dockerfile
README.md
docker-compose.yml
murdock.py
murdock/config.py
murdock/database/mongodb.py
murdock/database/postgresql.py
murdock/github.py
murdock/job.py
murdock/log.py
murdock/main.py
murdock/murdock.py
murdock/task.py
murdock/tests/test_github.py
murdock/tests/test_job.py
murdock/tests/test_murdock.py
requirements.txt

This commit rewrites the logging in the application to structured log
format. A pretty console printing and direct systemd-journal are available.
The logging can be switched via the MURDOCK_LOG_OUTPUT environment
variable. It defaults to `console` for development. Setting it to
`journal` sets it to output to the systemd journal.

Rewrite logging to structured log format

---

docker-compose.yml

Kind of useful when trying to start the frontend by calling the `murdock.py` application

compose: Include murdock.py in the volume binds

---

murdock/database/postgresql.py
murdock/tests/test_database_postgresql.py

This fixes the query when the `update_jobs` function is called to update the data inside the `jsonb` prinfo field (which is always the case). It also extends the postgres tests to prevent regressions.

 postgresql: Fix update query for jsonb field 

---

murdock/database/postgresql.py
murdock/tests/test_database_postgresql.py

The field translation must happen before the jsonb check so that fields such as the prinfo_state are not accidentally added to the jsonb in the update but are properly updating the specific fields
This commit also extends the test to prevent regressions

postgres: Translate update fields before jsonb check

---

murdock/github.py

This removes the content of the response from github after posting a reply to a topic. It still logs the content after an error. In case of success the full json of the post is in the reply which is quite a lot of data to log while it doesn't add anything

github: don't log full comment response from github

---

murdock/database/postgresql.py

Another small tuning of log messages
The terminate_connection callback is called on any closed connection to the database, also when the connection pool closes a connection by itself. This is thus not an issue and should not be logged at warning level

postgresql: Reduce logging of terminated connections

---

murdock/main.py

No need to show this endpoint in the api info

metrics: Exclude from schema info

---

murdock/job.py
murdock/tests/test_job.py

It is a bit harder to do the same with the remove dir function due to how it is used.

job: Make create_dir an instance method

---

murdock/murdock.py

Using the human readable string output here will only log the arguments used with the exception and not the exception type itself. Using repr adds the exception type.
```python
>>> try:
...   dict()['foo']
... except Exception as exc:
...   print(exc)
...   print(repr(exc))
... 
'foo'
KeyError('foo')
```

Murdock: use repr to log exceptions
